config/routes.rb
Rails.application.routes.draw do

  get 'listings/show'

  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to:'sessions#new'
  get '/login',	 to: 'sessions#create'
  get '/addlistings',	to: 'houses#new'
  
  
  delete '/logout',  to: 'sessions#destroy'
  
  post '/signup',  to: 'users#create'
  post '/login',	  to: 'sessions#create'
  post '/addlistings', to: 'houses#create'
  resources :users
  resources :houses
  resources :notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/house.rb
class House < ApplicationRecord

	belongs_to :user

	validates :house_type, presence: true
	validates :room, presence: true, numericality: { only_integer: true}
	validates :bathroom, presence: true, numericality: { only_integer: true}
	validates :price, presence: true, numericality: { only_integer: true}

	#house pictures
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	after_save :send_notification



	private


	def send_notification
		NotificationsWorker.perform_async(self.id)
	end
end

app/models/notification.rb
class Notification < ActiveRecord::Base

	belongs_to :user
	belongs_to :house

	validates :user, presence: true
	validates :house, presence: true
	
end

app/models/user.rb
class User < ApplicationRecord

	has_many :houses
	has_many :notifications

	before_save { email.downcase! }
	#name validation
	validates :name, presence: true, length: {maximum: 50}

	#email validation
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255},
		format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

	#password validation
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	validates :role, presence: true

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)                                       
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  before_action :user_is_logged_in, only: [:create, :edit, :update]
  def index
    @houses = House.includes(:user).all
  end

  

  def show
    @house = House.find_by(id: params[:id])
  end

  def new
    @house = House.new
  end

  

  def create
    @house = House.new(house_params)
    @house.user = current_user

    if @house.save
      
      flash.now[:success] = "Successfully create a house listing!"
      redirect_to @house
    else
      flash.now[:danger] = "Sorry failedd creating a house listing"
      render 'new'
    end
  end

  def edit
    @house = House.find(params[:id])
  end

  def update
    @house = House.find(params[:id])
    if @house.update_attributes(house_params)
      flash.now[:success] = "Your changes have been successfully saved!"
      redirect_to @house
    else
      flash.now[:danger] = "Sorry your changes have not been saved."
      render 'edit'
    end
  end

    private

    def house_params
      params.require(:house).permit(:house_type, :bathroom, :room, :price, :description, :user_id, :image)
    end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	def index
   		
  	end
  	def show
  		@houses = current_user.houses
 	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      	#login
  		log_in user
  		
  		redirect_back_or user
    else
    	flash.now[:danger] = "Invalid email/password combination!"
  		render 'new'
  	end
  end

  def destroy
  	log_out
  	redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_is_logged_in, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  def show
  	  @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		log_in @user
  		flash.now[:success] = "Welcome to the Elena's Realtors App!"
  		redirect_to @user
  	else
  		flash.now[:danger] = "Sorry your information was not valid"
  		render 'new'
  	end
  end

  def edit
  	@user = User.find(params[:id])
  end

   def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash.now[:success] = "Your changes have been successfully saved!"
      redirect_to @user
    else
    	flash.now[:danger] = "Sorry your changes have not been saved."
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :role)
    end

    

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title="")
		base_title = "Elena's Realtors App"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end


	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end
	  # Returns true if the given user is the current user.
 	def current_user?(user)
   	 	user == current_user
 	end

	def current_user_houses
		@current_user_house ||= @current_user.houses #House.find_by(user_id: session[:user_id])
	end

	def has_house?
		current_user.houses.any?
	end
	
	

	def user_is_logged_in
    	unless logged_in?
    		flash[:danger] = "Please log in."
    		redirect_to login_url
    	end
    end

	def is_current_user_seller?
		current_user.role == "Seller"
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	  # Redirects to stored location (or to the default).
	def redirect_back_or(default)
	   redirect_to(session[:forwarding_url] || default)
	   session.delete(:forwarding_url)
	end

	  # Stores the URL trying to be accessed.
	def store_location
	   session[:forwarding_url] = request.original_url if request.get?
	end
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, size: 80)
    	gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
   		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    	image_tag(gravatar_url, alt: user.name, class: "gravatar")
  	end
end

app/views/houses/_form.html.erb
<%= form_for(@house, html: { multipart: true }) do |f| %>
  	<%= render 'shared/house_error_messages' %>

	<%= f.label :house_type %>
	<%= f.select :house_type, ['', 'Detached', 'Semi-detached', 'Town'], {}, class: 'form-control' %>
	
	<%= f.label :room %>
	<%= f.select :room, ['', 0, 1, 2, 3, 4, 5], {},class: 'form-control' %>

	<%= f.label :bathroom %>
	<%= f.select :bathroom, ['', 0, 1, 2, 3, 4, 5], {},class: 'form-control' %>
	
	
	
	<%= f.label :price, "Price" %>
	<%= f.text_field :price, class: 'form-control' %>

	<%= f.label :description, "Description" %>
	<%= f.text_area :description , class: 'form-control', placeholder: "Leave a description.. " %>

	<%= f.file_field :image %>
	<div class="button_div">
	<%= f.submit "Submit", class: "btn btn-primary" %>
	</div>
<% end %>

app/views/houses/edit.html.erb
<% provide(:title, "Edit Listing") %>
<h1>Update your listing</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
  </div>
</div>

app/views/houses/index.html.erb
<% provide(:title, 'All Houses') %>
<h1>All houses</h1>
<div class="container">
	<% @houses.each do |house| %>
		<div class="row" style="border: 1px solid black;">
			<div class="col-md-6" >
  				House id:
  				<%= link_to house.id, house %>

  				<%= image_tag house.image.url(:medium)%>
			</div>
			<div class="col-md-4">
				<h2>Price : $<%= house.price %></h2>
				<h2>House Type : <%= house.house_type %></h2>
				<h2>Bathrooms : <%= house.bathroom %></h2>
				<h2>Bedrooms : <%= house.room %></h2>
			</div>
		</div>
	<% end %>
</div>

app/views/houses/new.html.erb
<%= provide(:title, "Add Listings") %>
<h1>Add Listings</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= render 'form' %>
  </div>
</div>

app/views/houses/show.html.erb
<%= provide(:title, "House Info") %>
<h1>House Info</h1>
<div class="container">

		<div class="ticket_info_container">
			<%= image_tag @house.image.url(:medium)%>
			<h2>House Id: <%= @house.id %></h2>
			<h2>Owner Name: <%= @house.user.name %> </h2>
			<h2>Owner Email: <%= @house.user.email %> </h2>
			<h2>Price : $<%= @house.price %></h2>
			<h2>House Type : <%= @house.house_type %></h2>
			<h2>Bathrooms : <%= @house.bathroom %></h2>
			<h2>Bedrooms : <%= @house.room %></h2>
			<h2>Description : <%= @house.description %></h2>
		</div>
	<% if current_user.id == @house.user_id %>
		<div class="button_div">
			<%= link_to "Edit", edit_house_path(@house), class: "btn btn-lg btn-primary" %>
		</div>
	
	<% end %>
</div>

app/views/layouts/_default_settings.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The realtor app from Elena Kim
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Realtor", root_path, id: "logo" %>
		<nav >
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Houses", houses_path %><li>
				<% if logged_in? %>
          			<li class="dropdown">
            		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
              			Account <b class="caret"></b>
            		</a>
            		<ul class="dropdown-menu">
	              <li><%= link_to "Profile", current_user %></li>
	              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
	              	<% if has_house? && is_current_user_seller? %>
	              		<li><%= link_to "My Listing",  listings_show_path%></li>
	              		<li><%= link_to "Add Listing", addlistings_path %></li>
	                <% elsif is_current_user_seller? %>
	              		<li><%= link_to "Add Listing", addlistings_path %></li>
	              	<% end %>
	             
	              <li class="divider"></li>
	              <li>
	                <%= link_to "Log out", logout_path, method: :delete %>
	              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
			</ul>
		</nav>
	</div>
</header>
<!-- house_path(current_user.houses.first) -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/default_settings' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
  	<% flash.each do |message_type, message| %>
    	<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/listings/index.html.erb
<% provide(:title, 'All Houses') %>
<h1>All houses</h1>

<ul class="houses">
  <% @houses.each do |house| %>
    <li>
      House id:
      <%= link_to house.id, house %>
    </li>
  <% end %>
</ul>

app/views/listings/show.html.erb
<% provide(:title, 'My Listings') %>
<h1>My Listings</h1>

<ul class="houses">
  <% @houses.each do |house| %>
    <li>
      House id:
      <%= link_to house.id, house %>
    </li>
  <% end %>
</ul>

app/views/pages/about.html.erb
<%= provide(:title, "About") %>
<h1>About</h1>

app/views/pages/contact.html.erb
<%= provide(:title, "Contact") %>
<div>
	<h1>Contact</h1>
	<p>Stuff goes here</p>
</div>

app/views/pages/home.html.erb
<%= provide(:title, "Home") %>
<div class="center jumbotron">
	<h1>Welcome to Elena's Realtors App</h1>
	<% if logged_in? %>
		<h2>Hello <%= @current_user.name %>!</h2>
	<% else %>
		<h2>Are you looking to sell a house or buy a house?</h2>
		<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	<% end %>
	
</div>
<div class ="home_search">
	<%= form_for(:house) do |f| %>
	<div class ="row">

		<%= f.search_field :address, class: "form-control", placeholder: "Search" %>
		<div class="col-sm-3">
	  	<%= f.label :type %>
	  	<%= f.select :type, ['Any', 'Detached', 'Semi-detached', 'Town'] %>
		</div>
		<div class="col-sm-3">
	  	<%= f.label :bathroom %>
	  	<%= f.select :bathroom, ['Any', 0, 1, 2, 3, 'More'], class: 'form-control' %>
		</div>
		<div class="col-sm-3">
	 	<%= f.label :room %>
	 	
	  	<%= f.select :room, ['Any', 0, 1, 2, 3, 'More'], class: 'form-control' %>
		</div>
		<div class="col-sm-3">
	  	<%= f.label :price, "Price" %>
	  	
	  	<%= f.select :price, ['Any', '0~100,000', '100,000~200,000','More'], class: 'form-control' %>
		</div>
	</div>
	 <div class="button_div">
	  <%= f.submit "Search", class: "btn btn-primary" %>
	  </div>
	<% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_house_error_messages.html.erb
<% if @house.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@house.errors.count, "error") %>.
    </div>
    <ul>
    <% @house.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :role, "User Type" , class: "control-label"%>
      <%= f.radio_button :role, "Buyer", :checked => true %>
      <%= f.label :role, "Buyer" , :value => "buyer", class: 'radio-inline'%>
      <%= f.radio_button :role, "Seller" %>
      <%= f.label :role, "Seller" , :value => "seller",class: 'radio-inline'%>
      <div class="button_div">    
            <%= f.submit "Submit", class: "btn btn-primary" %>
      </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= provide(:title, "Sign up") %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    
    <p>Already have an account? <%= link_to "Log In now", login_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
      	<%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <h2>
      	<%= @user.email %>
      </h2>
      <h2>
      	<%= @user.role %>
      </h2>
    </section>
  </aside>
</div>